debug=true

spring.application.name=usermanager
spring.profiles.active=@activatedproperties@

springdoc.api-docs.path=/api-docs

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

usermanager.imgur.accessToken=

