INSERT INTO DIGITAL_SERVICE_USER(USER_ID, USER_NAME, USER_PASSWORD) VALUES(199999, 'JOHN DOE', 'abcd');
INSERT INTO DIGITAL_SERVICE_USER(USER_ID, USER_NAME, USER_PASSWORD) VALUES(299999, 'JANE DOE', 'abcd');
