INSERT INTO DIGITAL_SERVICE_USER(USER_ID, USER_NAME, USER_PASSWORD, PHONE_NUMBER) VALUES(199999, 'JOHN DOE', 'abcd', '+17037550417') ON CONFLICT (USER_ID) DO NOTHING;
INSERT INTO DIGITAL_SERVICE_USER(USER_ID, USER_NAME, USER_PASSWORD) VALUES(299999, 'JANE DOE', 'abcd') ON CONFLICT (USER_ID) DO NOTHING;
