CREATE TABLE IF NOT EXISTS DIGITAL_SERVICE_USER(USER_ID INT PRIMARY KEY,
       USER_PASSWORD VARCHAR(255),
       USER_NAME VARCHAR(255));
CREATE TABLE IF NOT EXISTS DIGITAL_SERVICE_USER_PROFILE(PROFILE_ID INT PRIMARY KEY,
        PROFILE_URL VARCHAR(255));

