CREATE TABLE IF NOT EXISTS DIGITAL_SERVICE_USER(USER_ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       USER_PASSWORD VARCHAR(255),
       USER_NAME VARCHAR(255),
       PHONE_NUMBER VARCHAR(20),
       PROFILE_ID INT );
CREATE TABLE IF NOT EXISTS DIGITAL_SERVICE_USER_PROFILE(PROFILE_ID SERIAL PRIMARY KEY,
        PROFILE_URL VARCHAR(255));

 ALTER TABLE DIGITAL_SERVICE_USER
    ADD FOREIGN KEY (PROFILE_ID)
    REFERENCES DIGITAL_SERVICE_USER_PROFILE(PROFILE_ID);

-- Corrective for USER_ID columns created before this table had identity generation --
-- User.userId is mapped GenerationType.IDENTITY, which expects Postgres to generate
-- the PK; a plain INT column never did, so userRepository.save() on a new User (no ID
-- set) failed with a NOT NULL violation. No-op once the column is already an identity.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_attribute a
        JOIN pg_class c ON a.attrelid = c.oid
        WHERE c.relname = 'digital_service_user' AND a.attname = 'user_id' AND a.attidentity <> ''
    ) THEN
        ALTER TABLE DIGITAL_SERVICE_USER ALTER COLUMN USER_ID ADD GENERATED BY DEFAULT AS IDENTITY;
        PERFORM setval(pg_get_serial_sequence('digital_service_user', 'user_id'), COALESCE((SELECT MAX(USER_ID) FROM DIGITAL_SERVICE_USER), 1));
    END IF;
END $$;

